# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# # Will include all hosts the playbook is run on.
# # Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html
- name: "Build hosts file"
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups[hostfile_group] | default([]) }}"
